runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
- url: /script
  static_dir: script
- url: /images
  static_dir: images

- url: .*
  script: main.app
  http_headers:
    Access-Control-Allow-Origin: *

    
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: PIL
  version: "1.1.7"

